### ISSUE TITLE
[hydra] rajouter une colonne commentaire dans la table des exceptions

### ISSUE THREAD

**Issue by maudetes** [datagouv/hydra#190]
Il s'agirait d'un champ libre, permettant notamment d'ajouter le contexte de la mise en exception d'une ressource.
Utile pour comprendre des choix historiques et aussi dans le cas d'ajouts temporaires (exemple : pour un hackathon).

**Comment by bolinocroustibat** [comment]
PR here: https://github.com/datagouv/hydra/pull/191
