### ISSUE TITLE
Use an ORM?

### ISSUE THREAD

**Issue by abulte** [datagouv/hydra#29]
I guess we'll be writing more and more queries and an ORM could help making the code cleaner and avoiding errors. https://github.com/python-gino/gino is pretty nice and works with async.

**EDIT 2024/07/30 by @bolinocroustibat:**

Other favorite ORM options:
- [Piccolo ORM](https://piccolo-orm.com/) : async, many perks and integrated admin
- [Tortoise ORM](https://tortoise.github.io/) : supposedly the [fastest](https://github.com/tortoise/orm-benchmarks), async, quite popular (more stars on GitHub, and recommended by FastAPI creator - also I'm experienced on that one :) )

**Comment by bolinocroustibat** [comment]
Since we already use SQLalchemy in other parts of the code, we should use this existing ORM

**Comment by bolinocroustibat** [comment]
Not sure it's necessary anymore since https://github.com/datagouv/hydra/pull/55 and https://github.com/datagouv/hydra/pull/112 have been closed.
